---
- name: Backup RouterOS with custom module
  hosts: all
  gather_facts: false
  connection: network_cli
  
  vars:
    ansible_ssh_user: ansible
    ansible_ssh_password: ansible
    ansible_network_os: routeros
  
  tasks:
    - name: Backup RouterOS
      mtk_backup2:
        dest: config.txt
        username: "{{ ansible_ssh_user }}"
        password: "{{ ansible_ssh_password }}"