---
- name: Backup RouterOS with custom module
  hosts: all
  gather_facts: false
  connection: network_cli
  
  vars:
    ansible_ssh_user: ansible
  
  tasks:
    - name: Backup RouterOS
      mtk_backup:
        dest: config.txt
        username: "{{ ansible_username }}"